baseURL: https://armankolozyan.com
languageCode: en-us
build:
  writeStats: true
params:
  title: Arman Kolozyan
  description: Arman Kolozyan
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
    favicons:
      use: true
      metas: |2-
                <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
                <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
                <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
                <link rel="manifest" href="site.webmanifest">
                <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Arman Kolozyan"
    tagline: MSc Student Computer Science at Vrije Universiteit Brussel
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/arman-kolozyan-87a96a190/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/ArmanKolozyan"
        title: GitHub
      - icon: fas fa-envelope
        url: "mailto:arman.kolozyan@vub.be"
        title: Email
      - icon: fas fa-file-pdf
        url: "Resume_Arman_Kolozyan.pdf"
        title: Resume  
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: honors
    - item: volunteering
    - item: favorite_quotes
  aboutme:
    title: About Me
    icon: fas fa-user
    description: |
      I am a Computer Science Master's student from Belgium, studying at the <a href="https://www.vub.be/en/studying-vub/all-study-programmes-vub/bachelors-and-masters-programmes-vub/applied-sciences-and-engineering-computer-science/program/master/master-software-languages-and-software-engineering" target="_blank">Vrije Universiteit Brussel</a>. My research interests are in security, specifically in vulnerability analysis of network protocols and Zero-Knowledge Proofs (ZKPs). Currently, I am working on my master's thesis in collaboration with <a href="https://www.bell-labs.com/about/locations/antwerp-belgium" target="_blank">Nokia Bell Labs</a>, where I am investigating bugs in ZKP programs. Previously, I completed a research internship at <a href="https://www.esat.kuleuven.be/cosic/" target="_blank">KU Leuven’s COSIC group</a>, where I conducted a security analysis of the Matter standard for smart home devices.
  experience:  
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Security Research Intern
        dates: September 2024 - Present
        company: Nokia Bell Labs, Antwerpen
        details: |1-
          - Conducting research focused on the security analysis of Zero-Knowledge Proofs (ZKPs).
          - The goal is to identify vulnerabilities in ZKP programs, categorize them, and create a tool to detect
            those bugs.
          - The thesis ultimately aims to enhance the security of ZKP implementations and provide insights for
            developers in this field.

      - position: Security Research Intern
        dates: July 2024 - September 2024
        company: COSIC (KU Leuven), Leuven
        details: |1-
          - COSIC is a leading research institution in cryptography and software/hardware security.
          - Conducted an in-depth security analysis of the Matter standard for smart home communication, with
            the aim of identifying potential security weaknesses and vulnerabilities.
          - Performed formal verification of Matter’s protocols using automated tools, which involved modeling
            and verifying the protocols to uncover flaws.
          - Worked under the guidance of [Dave Singelée](https://scholar.google.be/citations?user=ekrwosIAAAAJ&hl=nl), [Georgio Nicolas](https://scholar.google.com/citations?user=l7vlhqgAAAAJ&hl=en), [Sayon Duttagupta](https://dblp.uni-trier.de/pid/313/5856.html) and Professor [Bart
            Preneel](https://scholar.google.com/citations?user=omio-RsAAAAJ&hl=nl), whose combined expertise was instrumental to the project.
          - This experience strengthened my skills in protocol security analysis and formal verification, and
            expanded my understanding of security challenges within the IoT field.

      - position: Summer School Participant
        dates: September 2024
        company: Technische Universität Darmstadt, Germany
        details: |1-
          - Attended the ACM Europe Summer School on Distributed and Replicated Environments (DARE) 2024 in
            Darmstadt, Germany, focused on advanced topics in distributed systems.
          - It offered me both theoretical and practical knowledge, with lectures focusing on consistency models,
            verification techniques, and programming models for distributed applications.
          - Participated in hands-on sessions and worked on a small research project, deepening my understanding
            of current challenges and solutions in distributed systems.

      - position: Programming Lecturer 
        dates: November 2021 - November 2024
        company: Vrije Universiteit Brussel
        details: |1-
          - Lecturer for additional programming classes (in the programming language Scheme), organized for first
            year Computer Science students at my university. I was allowed to teach these exercise sessions
            together with a few other fellow students.
          - Always prepared slides to help the students refresh the necessary theory. Then we solved exercises in
            preparation for the exam.
          - During the coronavirus period, I gave a session online and an on-campus session every other week. 
          - If the session went online, I had the students share their code via a code-sharing website where I
            provided comments to help them make progress.

      - position: Lecturer of Mathematics 
        dates: September 2022 - September 2023
        company: Vrije Universiteit Brussel
        details: |1-
          - Taught the following topics of mathematics for both mathematics and non-mathematics background
            students: Linear Algebra, Analysis, Functions, Plane Geometry, Three Dimensional Geometry.
          - This was my first experience teaching a class of more than 40 students.

      - position: Webmaster 
        dates: April 2022 - September 2022
        company: Vrije Universiteit Brussel
        details: |1-
          - Helping with the development of the new website of the Vrije Universiteit Brussel (VUB).
            Regularly making small adjustments to the site, creating new events, etc.
          - Following up a ticketing system and resolving tickets from VUB staff and external people.

      - position: Integration of Usolv-it Exercises into the Canvas Learning Platform 
        dates: July 2022
        company: Vrije Universiteit Brussel
        details: |1-
          - Writing mathematics problems in LaTeX format.
          - Managing mathematics assignments in Usolv-it.
          - Converting Usolv-it assignments into tests and then migrating these to the Canvas learning platform.

      - position: Organization of Pretests in Mathematics, Chemistry and Physics 
        dates: September 2021
        company: Vrije Universiteit Brussel
        details: |1-
          - Correcting pre-tests (which test the prior knowledge of first-year university students).
          - Supervising when the students take their tests.

      - position: Teaching Assistant of Preparation/Bridge Course in Mathematics 
        dates: August 2021 - September 2021
        company: Vrije Universiteit Brussel
        details: |1-
          - Organizing live question sessions.
          - Answering students' questions on discussion fora.
          - Correcting tests.
          - Updating the solutions of exercises on the website of the mathematics book 'Wiskundige
            basisvaardigheden' (basiswiskunde.be).

      - position: API Inventarisation 
        dates: August 2022
        company: Argenta, Antwerpen
        details: |1-
          - Argenta is a Belgian bank and insurance group offering financial services in Belgium, the Netherlands,
            and Luxembourg.
          - Spent a month in their IT Shared Service Integration department, assisting with the
            identification of available APIs.
          - Created a comprehensive list of technical and functional descriptions of APIs and researched optimal
            tools for inventory setup and maintenance.
          - Worked three days per week at the headquarters in Antwerp and two days from home, with weekly
            follow-ups.
          - This role brought me a first business experience in IT, improved my skills in conveying information
            smoothly and correctly, enhanced my ability to ask targeted questions to colleagues, and introduced
            me to agile/scrum methodologies.

      - position: Logistics and Outlet Employee 
        dates: July 2020 - September 2020
        company: ZEB, Merchtem
        details: |1-
          - RFID, Sorter, Optical Scanning.

      - position: Helpdesk 
        dates: March 2019
        company: FAMIFED, Brussel
        details: |1-
          - Assisting Famiris (federal child benefits agency) staff with technical problems.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Master's degree in Software Engineering
        college: Vrije Universiteit Brussel
        dates: 2023 - 2025
        distinction: currently Greatest Distinction (summa cum laude)
      - degree: Bachelor’s degree in Computer Science
        college: Vrije Universiteit Brussel
        dates: 2020 - 2023
        distinction: Greatest Distinction (summa cum laude)
      - degree: Science-Mathematics (8 hours of math per week)
        college: GO! Atheneum Emanuel Hiel
        dates: 2014 - 2020
        distinction: Greatest Distinction (summa cum laude)
  publication:
    title: Publications
    icon: fas fa-book
    list:
      - title: "How to Become a Memory Champion?"
        magazine: "EOS Wetenschap"
        date: "July 2020" 
        description: |
          EOS Wetenschap is a renowned Belgian monthly magazine that covers the latest advancements in science for a broad audience. "Arman Kolozyan is 19 years old. He graduated in Science-Mathematics from GO! Atheneum Emanuel Hiel and has always dreamed of having a fantastic memory. Can anyone become a memory champion? He researched this question and wrote an article on his findings."             
          <br>You can read the article <a href="https://www.eoswetenschap.eu/psyche-brein/hoe-word-je-een-geheugenkampioen" target="_blank">here</a> (it is in Dutch).

  honors:
      title: Honors
      icon: fas fa-award
      list:
        - title: Winner Cyber Security Challenge Belgium 2024 (qualifiers)
          details: |1-
            Team competition for Belgian students about cyber security. Our team secured the first place out of 286
              teams in the qualifiers.

        - title: Finalist Cyber Security Challenge Belgium 2023
          details: |1-
            Team competition for Belgian students about cyber security.

        - title: Pre-Finalist Cyber Security Challenge Belgium 2022
          details: |1-
            Team competition for Belgian students about cyber security.

        - title: Winner Vrije Universiteit Brussel (VUB) CTF 2021
          details: |1-
            Capture The Flag (CTF) is a competition in which different teams solve tasks related to cyber security.

        - title: Interview in BRUZZ (Belgian magazine)
          details: |1-
            After I successfully completed my first academic year, I was interviewed in <a href="https://www.bruzz.be/onderwijs/het-corona-effect-meer-studenten-kiezen-voor-informatica-2021-09-28" target="_blank">this Belgian news article</a>
              about the Computer Science major and my academic achievements. I was also later invited for a radio interview.

        - title: Finalist Wiskunnend Wiske Wedstrijd 2020
          details: |1-
            Competition in which challenging mathematics questions must be solved by fifth and sixth year
              secondary students.

  volunteering:
      title: Volunteering
      icon: fas fa-hands-helping
      list:
        - position: Corporate Relations, Lectures & Seminars
          dates: September 2023 - Present
          organization: Infogroep
          details: |1-
            Infogroep is the student group founded for the students of Computer Science at the Vrije Universiteit
              Brussel (VUB). At Infogroep, we organize activities such as classes and seminars, competitions, a gaming
              tournament, a job fair, etc.

        - position: Student Representative in Study Programme Committee
          dates: October 2022 - Present
          organization: Vrije Universiteit Brussel
          details: |1-
            Serving on the Study Programme Committee as Student Representative, actively contributing to the
              enhancement of academic programs and the overall student experience. Collaborating with faculty,
              administration, and fellow students to advocate for student needs, voice concerns, and promote positive
              changes within the educational institution.

        - position: Student Volunteer at Computer Science Workshop
          dates: March 2024
          organization: Brussels Workshop on Real-Time Scheduling and Operating System Synergies
          details: |1-
            Assisted attendees in navigating the university campus.

        - position: Corporate Relations, Public Relations and Job Fair Organizer
          dates: December 2021 - September 2023
          organization: Infogroep
          details: |1-
            Served as the head of the annual job fair organized by our student association. In order to make the job
              fair a success, I ensured extensive promotion across various academic disciplines, which involved
              promotion at the beginning of lectures, running paid Facebook advertisements, and more. I made
              concerted efforts to attract a diverse range of appealing companies to participate. Ultimately, the job fair
              proved to be a great success, with over 100 attendees, 15+ participating companies, and with more than
              150 student CVs submitted.

        - position: Student Volunteer at Gaming Event
          dates: October 2022
          organization: GameForce
          details: |1-
            GameForce is the largest gaming event in the Benelux. As a volunteer, I had the responsibility to stand at
              various (gaming) booths, attract visitors to these booths, and provide the necessary assistance to the
              visitors.

        - position: Student Volunteer at Computer Science Conference
          dates: September 2022
          organization: International Conference on Managed Programming Languages & Runtimes
          details: |1-
            - Room Support: Assisting presenters in the conference room and troubleshooting technical issues,
              passing the microphone for questions, etc.
            - Outside Support: helping in the main hall at the registration desk, setting up coffee breaks, etc.
  favorite_quotes:
    title: Favorite Motivational Quotes
    icon: fas fa-quote-left
    intro: |
      Below is a collection of my favorite motivational quotes (well... some might be more inspirational than others). I have included links for more information about the authors, though for a few lesser-known ones, I simply referenced where I first encountered them.
    list:
      - quote: "Fate loves the fearless."
        source: "https://www.goodreads.com/quotes/14333-fate-loves-the-fearless#:~:text=Quote%20by%20James%20Russell%20Lowell%3A%20%E2%80%9CFate%20loves%20the%20fearless.%E2%80%9D"

      - quote: "Destiny doesn't make mistakes."
        source: "https://www.brainyquote.com/quotes/dustin_poirier_1083373"

      - quote: "The reasonable man adapts himself to the world: the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man."
        source: "https://www.goodreads.com/quotes/536961-the-reasonable-man-adapts-himself-to-the-world-the-unreasonable"

      - quote: "I saw the angel in the marble and carved until I set him free."
        source: "https://www.goodreads.com/quotes/1161553-i-saw-the-angel-in-the-marble-and-carved-until"

      - quote: "It’s tough to get out of bed to do roadwork at 5 am when you’ve been sleeping in silk pajamas."
        source: "https://quotefancy.com/quote/1220835/Marvin-Hagler-It-s-tough-to-get-out-of-bed-to-do-roadwork-at-5-am-when-you-ve-been"

      - quote: "I’ll be fine once I get it. I’ll be good."
        source: "https://genius.com/550139"

      - quote: "Destiny doesn't do home visits."
        source: "https://www.goodreads.com/quotes/768202-destiny-doesn-t-do-home-visits-you-have-to-go-for"

      - quote: "If it’s meant for me, it won’t miss me."
        source: "https://www.instagram.com/dustinpoirier/p/C56Kgonr5_S/"

      - quote: "Men are haunted by the vastness of eternity."
        source: "https://www.goodreads.com/quotes/7624973-men-are-haunted-by-the-vastness-of-eternity-and-so"

      - quote: "Setting a goal, giving your all, and coming up short is scary. That’s what makes it great, that’s what makes you give your all to the project. And I think my fear is why I have done so well."
        source: "https://youtu.be/1QU75E7xGj8?t=40"

      - quote: "It was time to marry the game and I said, \"Yeah, I do.\""
        source: "https://genius.com/Meek-mill-dreams-and-nightmares-intro-lyrics#:~:text=It%20was%20time%20to%20marry%20the%20game%20and%20I%20said%2C%20%22Yeah%2C%20I%20do%22"

      - quote: "It’s the curse of the standard."
        source: "https://genius.com/13029487"

      - quote: "Now the sky's blackening. I know the mark’s high, butterflies rip apart my stomach."
        source: "https://genius.com/13029859"

      - quote: "If you want it, you gotta see it with a clear-eyed view."
        source: "https://genius.com/Meek-mill-dreams-and-nightmares-intro-lyrics#:~:text=If%20you%20want%20it%2C%20you%20gotta%20see%20it%20with%20a%20clear%2Deyed%20view"

      - quote: "To me fearless isn't not having fears, it's not that you're not afraid of anything. I think that being fearless is having a lot of fears, but you jump anyway."  
        source: https://www.goodreads.com/quotes/369888-to-me-fearless-isn-t-not-having-fears-it-s-not-that
